name: Terraform Deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'prod'
        type: choice
        options:
          - prd
          - non-prd  
permissions:
    id-token: write   # This is required for requesting the JWT..
    contents: read
    packages: write
    pull-requests: write 
    pages: write

jobs:
  harness_plan:
    name: Harness Plan
    if: github.ref == 'refs/heads/main'
    uses: "./.github/workflows/plan.yml"
    with:
      gh_environment: prd
      # workdir_path: 'organizations'
    secrets:
      TF_VAR_HARNESS_ENDPOINT: ${{ vars.TF_VAR_HARNESS_ENDPOINT }}
      TF_VAR_HARNESS_ACCOUNT_ID: ${{ vars.TF_VAR_HARNESS_ACCOUNT_ID }}
      TF_VAR_HARNESS_PLATFORM_API_KEY: ${{ vars.TF_VAR_HARNESS_PLATFORM_API_KEY }}
      # AC_HARNESS_TF_MODULES_PVT_KEY: ${{ vars.AC_HARNESS_TF_MODULES_PVT_KEY }}
      backendAzureRmResourceGroupName: ${{ vars.backendAzureRmResourceGroupName }}
      backendAzureRmStorageAccountName: ${{ vars.backendAzureRmStorageAccountName }}
      backendAzureRmContainerName: ${{ vars.backendAzureRmContainerName }}
      backendAzureRmKey: ${{ vars.backendAzureRmKey }}
      client_id: ${{ vars.client_id }}
      tenant_id: ${{ vars.tenant_id }}
      
  harness_apply:
    name: Harness Apply
    needs: harness_plan
    uses: "./.github/workflows/apply.yml"
    with:
      gh_environment: prd
      # workdir_path: 'organizations'
    secrets:
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_OIDC_ROLE_ARN_NONPROD: ${{ vars.AC_ENTERPRISETOOLS_PROD_INFRA_OIDC_ROLE_ARN }}
      S3_BACKEND_ROLE_PROD_ARN: ${{ vars.S3_BACKEND_ROLE_PROD_ARN }}
      TF_VAR_HARNESS_ENDPOINT: ${{ vars.TF_VAR_HARNESS_ENDPOINT }}
      TF_VAR_HARNESS_ACCOUNT_ID: ${{ vars.TF_VAR_HARNESS_ACCOUNT_ID }}
      TF_VAR_HARNESS_PLATFORM_API_KEY: ${{ secrets.TF_VAR_HARNESS_PLATFORM_API_KEY }}
      AC_HARNESS_TF_MODULES_PVT_KEY: ${{ secrets.AC_HARNESS_TF_MODULES_PVT_KEY }}
